import type { PublicPlace } from "./places.functions";
import winebar from "@/assets/demo-winebar.jpg";
import bakery from "@/assets/demo-bakery.jpg";
import ramen from "@/assets/demo-ramen.jpg";
import viewpoint from "@/assets/demo-viewpoint.jpg";

/**
 * Placeholder pins shown while the map has no real pins yet.
 * They disappear as soon as the first real place is saved.
 */
export const DEMO_PLACES: PublicPlace[] = [
  {
    id: "demo-1",
    name: "Bar Alma",
    googlePlaceId: null,
    address: "Rua da Boavista 22, Lisbon",
    city: "Lisbon",
    country: "Portugal",
    lat: 38.7092,
    lng: -9.1493,
    rating: 9.2,
    priceLevel: 2,
    tags: ["wine", "late night", "date night"],
    note: "Placeholder note — tiny marble counter, no menu, just ask what's open. Sit at the far end by the window and order whatever the orange wine of the night is. Best around 10pm when the room fills up.",
    visitedOn: "2025-05-18",
    photos: [winebar],
  },
  {
    id: "demo-2",
    name: "Padaria do Bairro",
    googlePlaceId: null,
    address: "Praça das Flores 8, Lisbon",
    city: "Lisbon",
    country: "Portugal",
    lat: 38.7157,
    lng: -9.1512,
    rating: 8.6,
    priceLevel: 1,
    tags: ["breakfast", "coffee", "cheap"],
    note: "Placeholder note — pastéis straight out of the oven at 8:30. Stand at the counter, order a bica, don't take it to go.",
    visitedOn: "2025-05-19",
    photos: [bakery],
  },
  {
    id: "demo-3",
    name: "Menya Kotori",
    googlePlaceId: null,
    address: "2 Chome, Shinjuku, Tokyo",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6938,
    lng: 139.7036,
    rating: 9.5,
    priceLevel: 1,
    tags: ["ramen", "solo dinner", "queue"],
    note: "Placeholder note — nine seats, ticket machine at the door. Shio over shoyu. Twenty minute queue before 7pm, none after 9.",
    visitedOn: "2024-11-02",
    photos: [ramen],
  },
  {
    id: "demo-4",
    name: "Mirador de la Bahía",
    googlePlaceId: null,
    address: "Carrer del Mirador, Palma",
    city: "Palma",
    country: "Spain",
    lat: 39.5663,
    lng: 2.6502,
    rating: 8.9,
    priceLevel: null,
    tags: ["view", "sunset", "walk"],
    note: "Placeholder note — twenty minutes uphill from the old town, best an hour before sunset. Bring something to drink, there's nothing up there.",
    visitedOn: "2025-07-06",
    photos: [viewpoint],
  },
  {
    id: "demo-5",
    name: "Café Kollwitz",
    googlePlaceId: null,
    address: "Kollwitzstraße 45, Berlin",
    city: "Berlin",
    country: "Germany",
    lat: 52.5372,
    lng: 13.4192,
    rating: 8.1,
    priceLevel: 2,
    tags: ["coffee", "work spot", "brunch"],
    note: "Placeholder note — big tables, good light, nobody rushes you. Sunday market outside so go early or don't go at all.",
    visitedOn: "2025-03-22",
    photos: [],
  },
  {
    id: "demo-6",
    name: "The Harbour Room",
    googlePlaceId: null,
    address: "Pier 3, Sydney",
    city: "Sydney",
    country: "Australia",
    lat: -33.8568,
    lng: 151.2093,
    rating: 9.0,
    priceLevel: 3,
    tags: ["seafood", "special occasion", "view"],
    note: "Placeholder note — worth the splurge once. Ask for a table on the left side of the room, that's where the water view is.",
    visitedOn: "2024-12-30",
    photos: [],
  },
];
